# Generated by Django 2.2.14 on 2020-12-07 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='publicaciones',
        ),
    ]
