# Generated by Django 2.2.14 on 2020-12-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField()),
                ('tags', models.ManyToManyField(related_name='tags', to='tags.Tags')),
            ],
        ),
    ]
