# Generated by Django 2.2.14 on 2020-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_remove_comentario_publicaciones'),
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='comentarios',
            field=models.ManyToManyField(related_name='publicaciones', to='comentarios.Comentario'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tags',
            field=models.ManyToManyField(related_name='publicaciones', to='tags.Tags'),
        ),
    ]
